### ISSUE TITLE
How should I use it

### ISSUE THREAD

**Issue by Digital-IDE** [microdynamics-cpu/tree-core-ide#2]
As the title suggests, how do I use it correctly? There are bugs when I debug it and when I package it. Finally, is there a preview of waveform and schematic in engineering and how to use them correctly?

**Comment by maksyuki** [comment]
Thanks for your issue. As you said, there are some bugs and can not be used. The most important reason is that this project is still under development now. It means not a pre-release with bugs-free version can be published to public. So, it will take a while:smile:.
